# Generated by Django 5.1.4 on 2025-10-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('archetype', models.CharField(default='default archetype', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('polygon_geometry', models.JSONField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('point', 'Point Facility'), ('polygon', 'Polygon Asset')], default='point', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['session_key'], name='climate_haz_session_ef537d_idx'), models.Index(fields=['asset_type'], name='climate_haz_asset_t_904e03_idx')],
            },
        ),
        migrations.CreateModel(
            name='HazardAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(max_length=50)),
                ('scenario', models.CharField(default='current', max_length=50)),
                ('result_data', models.JSONField(default=dict)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_results', to='climate_hazards_analysis_v2.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'hazard_type', 'scenario'], name='climate_haz_asset_i_b2512c_idx')],
                'unique_together': {('asset', 'hazard_type', 'scenario')},
            },
        ),
    ]
