# Generated by Django 5.1.4 on 2025-10-28 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_hazards_analysis_v2', '0001_create_asset_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GranularAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('grid_row', models.IntegerField()),
                ('grid_col', models.IntegerField()),
                ('grid_spacing', models.FloatField()),
                ('hazard_type', models.CharField(max_length=50)),
                ('scenario', models.CharField(default='current', max_length=50)),
                ('result_data', models.JSONField(default=dict)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(max_length=50)),
                ('scenario', models.CharField(default='current', max_length=50)),
                ('grid_rows', models.IntegerField()),
                ('grid_cols', models.IntegerField()),
                ('grid_spacing', models.FloatField()),
                ('min_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('min_lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('max_lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('heatmap_values', models.JSONField(default=list)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('mean_value', models.FloatField(blank=True, null=True)),
                ('median_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='granular_analysis_progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='granular_analysis_status',
            field=models.CharField(choices=[('none', 'No Granular Analysis'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='granular_grid_points_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='granular_grid_spacing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_granular_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['granular_analysis_status'], name='climate_haz_granula_0f8cbf_idx'),
        ),
        migrations.AddField(
            model_name='granularanalysisresult',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granular_results', to='climate_hazards_analysis_v2.asset'),
        ),
        migrations.AddField(
            model_name='heatmapdata',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='climate_hazards_analysis_v2.asset'),
        ),
        migrations.AddIndex(
            model_name='granularanalysisresult',
            index=models.Index(fields=['asset', 'hazard_type', 'scenario'], name='climate_haz_asset_i_9302af_idx'),
        ),
        migrations.AddIndex(
            model_name='granularanalysisresult',
            index=models.Index(fields=['asset', 'grid_row', 'grid_col'], name='climate_haz_asset_i_f707f2_idx'),
        ),
        migrations.AddIndex(
            model_name='granularanalysisresult',
            index=models.Index(fields=['processing_status'], name='climate_haz_process_92029a_idx'),
        ),
        migrations.AddIndex(
            model_name='granularanalysisresult',
            index=models.Index(fields=['latitude', 'longitude'], name='climate_haz_latitud_2dc06a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='granularanalysisresult',
            unique_together={('asset', 'latitude', 'longitude', 'hazard_type', 'scenario')},
        ),
        migrations.AddIndex(
            model_name='heatmapdata',
            index=models.Index(fields=['asset', 'hazard_type', 'scenario'], name='climate_haz_asset_i_26c738_idx'),
        ),
        migrations.AddIndex(
            model_name='heatmapdata',
            index=models.Index(fields=['processing_status'], name='climate_haz_process_3a2653_idx'),
        ),
        migrations.AddIndex(
            model_name='heatmapdata',
            index=models.Index(fields=['hazard_type'], name='climate_haz_hazard__08b9ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heatmapdata',
            unique_together={('asset', 'hazard_type', 'scenario')},
        ),
    ]
