# Generated by Django 5.1.4 on 2025-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_hazards_analysis_v2', '0002_granularanalysisresult_heatmapdata_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='climate_haz_session_ef537d_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='session_key',
        ),
        migrations.AddField(
            model_name='asset',
            name='analysis_version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Batch identifier for bulk operations', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(blank=True, help_text='Asset owner or organization identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Overall data quality score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='source',
            field=models.CharField(blank=True, help_text='Source system or upload identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner'], name='climate_haz_owner_580fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['source'], name='climate_haz_source_dbddb7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['batch_id'], name='climate_haz_batch_i_7e1e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['created_at'], name='climate_haz_created_1deaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['last_analysis_date'], name='climate_haz_last_an_370ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_validated'], name='climate_haz_is_vali_862f79_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('quality_score__isnull', True), models.Q(('quality_score__gte', 0), ('quality_score__lte', 100)), _connector='OR'), name='valid_quality_score'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('granular_analysis_progress__gte', 0), ('granular_analysis_progress__lte', 100)), name='valid_progress_percentage'),
        ),
    ]
