# Generated by Django 5.1.4 on 2025-11-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_hazards_analysis_v2', '0003_remove_session_dependencies_add_owner_tracking'),
    ]

    operations = [
    ]
