# Generated by Django 5.1.4 on 2025-11-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_hazards_analysis_v2', '0004_add_temp_session_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='has_session_independent_analysis',
            field=models.BooleanField(default=False, help_text='Whether this asset has analysis results that can be overridden without session'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_analysis_session_key',
            field=models.CharField(blank=True, help_text='Last session key that performed analysis on this asset', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='workflow_state',
            field=models.CharField(choices=[('uploaded', 'Data Uploaded'), ('hazards_selected', 'Hazards Selected'), ('analysis_complete', 'Analysis Complete'), ('overrides_applied', 'Overrides Applied'), ('finalized', 'Finalized')], default='uploaded', help_text='Current state in the analysis workflow', max_length=20),
        ),
        migrations.CreateModel(
            name='OverrideValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, max_length=50, null=True)),
                ('column_name', models.CharField(max_length=255)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('override_value', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_identifier', models.CharField(blank=True, help_text='User session ID or identifier', max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for tracking', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this override is currently active')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_applied', 'Auto Applied')], default='auto_applied', max_length=20)),
                ('analysis_version', models.CharField(blank=True, max_length=20, null=True)),
                ('scenario', models.CharField(default='current', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='climate_hazards_analysis_v2.asset')),
            ],
            options={
                'verbose_name': 'Override Value',
                'verbose_name_plural': 'Override Values',
                'indexes': [models.Index(fields=['asset', 'column_name', 'is_active'], name='climate_haz_asset_i_bfd187_idx'), models.Index(fields=['asset', 'hazard_type'], name='climate_haz_asset_i_a4f1e1_idx'), models.Index(fields=['user_identifier'], name='climate_haz_user_id_e01029_idx'), models.Index(fields=['session_key'], name='climate_haz_session_d6e218_idx'), models.Index(fields=['created_at'], name='climate_haz_created_5b22b4_idx'), models.Index(fields=['approval_status'], name='climate_haz_approva_55610a_idx')],
                'unique_together': {('asset', 'column_name', 'hazard_type', 'scenario', 'is_active')},
            },
        ),
    ]
