# Generated by Django 5.1.4 on 2026-01-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='asset_name', max_length=255)),
                ('archetype', models.CharField(blank=True, db_column='asset_archetype', default='default archetype', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON geometry or point coordinate payload for this asset.', null=True)),
                ('polygon_geometry', models.JSONField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('point', 'Point'), ('polygon', 'Polygon'), ('granular', 'Granular Point')], max_length=50)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('upload', 'Upload'), ('map_click', 'Map Click'), ('draw_polygon', 'Draw Polygon'), ('manual_point', 'Manual Point'), ('manual_polygon', 'Manual Polygon'), ('uploaded_file', 'Uploaded File'), ('session_polygon_workflow', 'Session Polygon Workflow')], max_length=50, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('granular_analysis_enabled', models.BooleanField(default=False)),
                ('has_granular_analysis', models.BooleanField(default=False)),
                ('granular_analysis_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('granular_grid_spacing', models.FloatField(blank=True, null=True)),
                ('granular_analysis_progress', models.FloatField(default=0.0)),
                ('granular_grid_points_count', models.IntegerField(default=0)),
                ('has_session_independent_analysis', models.BooleanField(default=False)),
                ('workflow_state', models.CharField(default='new', max_length=100)),
                ('last_analysis_session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
